[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#E03A3E"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ffffff"
font = "sans serif"
